Added cart and wishlist page
sashaboi/ecomm-store pull request #2
Opened 2022-02-13 21:25 UTC by sashaboi

Cart and wishlist page added.

2022-02-13 22:22 UTC, vikrantkode requested changes
suggested some change
in UI, border radius is used for buttons in cart and for login is different. (make them same - personal suggestion.)

2022-02-13 22:22 UTC, vikrantkode commented on cart.html
> +                        <div class="badge-number">
Avoid inline style.

2022-02-13 22:22 UTC, vikrantkode commented on cart.html
> +                        <div class="badge-number">
same here

2022-02-13 22:22 UTC, vikrantkode commented
Overall looks good to me.

2022-02-14 03:45 UTC, raieegulhane reviewed
Overall looks good. There are 2 buttons for cart in preview. One icon and another normal button. Have any one.

2022-02-14 03:45 UTC, raieegulhane commented on styles.css
> +    background-color: rgba(0,0,0,0) !important;
Try not to use !important in code unless absolutely necessary.

2022-02-20 11:13 UTC, merged